[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "npm install -g concurrently",
  "cd backend && npm install",
  "cd frontend && npm install"
]

[phases.build]
cmds = [
  "cd backend && npm run build",
  "cd frontend && npm run build",
  "cd backend && npm prune --production",
  "cd frontend && npm prune --production"
]

[start]
cmd = "npm run start"
